/**
 * Program catalog rows (UI mock list until product/API owns all fields).
 * Used to build stub list rows in data.js alongside the full Foundations mock.
 */

export const PROGRAM_CATALOG = [
  {
    name: "28-Day Full Body Foundations",
    primaryGoal: "Weight loss, general fitness, strength",
    locationTag: "🏠 Home Friendly",
    workoutSkills: "Beginner",
    preference: "Weight Lifting",
    frequency: "3 days/week",
  },
  {
    name: "8-Week Intermediate Strength",
    primaryGoal: "Weight loss, general fitness, strength",
    locationTag: "🏋 Commercial Gym / Home Gym",
    workoutSkills: "Intermediate",
    preference: "Weight Lifting",
    frequency: "4 days/week",
  },
  {
    name: "8-Week Elite Strength",
    primaryGoal: "Weight loss, strength",
    locationTag: "🏋 Commercial Gym Required",
    workoutSkills: "Advanced",
    preference: "Weight Lifting",
    frequency: "5–6 days/week",
  },
  {
    name: "Low-Impact Cardio: 28-Day Ignite",
    primaryGoal: "Weight loss, general fitness, endurance",
    locationTag: "🏠 Home Friendly",
    workoutSkills: "Beginner",
    preference: "HIIT",
    frequency: "3 days/week",
  },
  {
    name: "Shred & Burn HIIT",
    primaryGoal: "Weight loss, general fitness, endurance",
    locationTag: "🏠 Home Friendly / No Equipment",
    workoutSkills: "Intermediate",
    preference: "HIIT",
    frequency: "3 days/week",
  },
  {
    name: "Elite Metabolic",
    primaryGoal: "Weight loss, endurance",
    locationTag: "🏋 Commercial Gym / Outdoor",
    workoutSkills: "Advanced",
    preference: "HIIT",
    frequency: "4 days/week",
  },
  {
    name: "Bodyweight Basics",
    primaryGoal: "Weight loss, strength, general fitness",
    locationTag: "🏠 Home Friendly / No Equipment",
    workoutSkills: "Beginner",
    preference: "Functional Movement",
    frequency: "3 or 4 days/week",
  },
  {
    name: "Core & Flow",
    primaryGoal: "General fitness",
    locationTag: "🏠 Home Friendly / 🏋 Commercial Gym",
    workoutSkills: "Beginner or Intermediate",
    preference: "Functional Movement",
    frequency: "ANY",
  },
  {
    name: "Functional Strength and Mastery",
    primaryGoal: "Strength",
    locationTag: "Commercial Gym",
    workoutSkills: "Advanced",
    preference: "Functional Movement",
    frequency: "4 days/week",
  },
  {
    name: "Crossfit: The United Frontier",
    primaryGoal: "ANY",
    locationTag: "Commercial Gym",
    workoutSkills: "ANY",
    preference: "Crossfit",
    frequency: "4 days/week",
  },
  {
    name: "15-Minute Quick Hits",
    primaryGoal: "ANY",
    locationTag: "🏠 Home Friendly / No Equipment",
    workoutSkills: "ANY",
    preference: "QUICKIES",
    frequency: "ANY",
  },
  {
    name: "Prenatal: The Radiant Forge",
    primaryGoal: "ANY",
    locationTag: "🏠 Home Friendly",
    workoutSkills: "Beginner / Intermediate",
    preference: "Prenatal / Postpartum",
    frequency: "ANY",
  },
  {
    name: "12-Week Shred To Stage",
    primaryGoal: "Strength, weight loss",
    locationTag: "🏋 Commercial Gym Required",
    workoutSkills: "Intermediate or Advanced",
    preference: "Weight Lifting",
    frequency: "5–6 days/week",
  },
];
