export const MOCK_NUTRITION_ITEMS = [
  {
    id: 1,
    foodItem: "Grilled Chicken Breast",
    category: "Lunch",
    mealType: "Non-Vegetarian",
    calories: 231,
    protein: 43.5,
    carbs: 0,
    fats: 5,
    status: "Active",
    createdAt: "2025-12-10",
    description: "Lean protein source, perfect for muscle building and weight management.",
    alternateFood: "Tofu",
  },
  {
    id: 2,
    foodItem: "Oatmeal with Berries",
    category: "Breakfast",
    mealType: "Vegetarian",
    calories: 307,
    protein: 10.2,
    carbs: 54.8,
    fats: 5.4,
    status: "Active",
    createdAt: "2025-12-09",
    description: "High-fiber breakfast option with antioxidants from berries.",
    alternateFood: "Quinoa Bowl",
  },
  {
    id: 3,
    foodItem: "Salmon with Vegetables",
    category: "Dinner",
    mealType: "Non-Vegetarian",
    calories: 412,
    protein: 35.2,
    carbs: 12.5,
    fats: 24.8,
    status: "Active",
    createdAt: "2025-12-08",
    description: "Rich in omega-3 fatty acids, excellent for heart health.",
    alternateFood: "Tuna Steak",
  },
  {
    id: 4,
    foodItem: "Greek Yogurt Bowl",
    category: "Snack",
    mealType: "Vegetarian",
    calories: 150,
    protein: 15,
    carbs: 12,
    fats: 4,
    status: "Active",
    createdAt: "2025-12-07",
    description: "High-protein snack with probiotics for gut health.",
    alternateFood: "Cottage Cheese",
  },
  {
    id: 5,
    foodItem: "Quinoa Salad",
    category: "Lunch",
    mealType: "Vegan",
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fats: 3.6,
    status: "Active",
    createdAt: "2025-12-06",
    description: "Complete protein source with all essential amino acids.",
    alternateFood: "Brown Rice Bowl",
  },
  {
    id: 6,
    foodItem: "Protein Smoothie",
    category: "Snack",
    mealType: "Vegetarian",
    calories: 280,
    protein: 25,
    carbs: 35,
    fats: 5,
    status: "Active",
    createdAt: "2025-12-05",
    description: "Quick and convenient post-workout recovery drink.",
    alternateFood: "Protein Shake",
  },
  {
    id: 7,
    foodItem: "Egg White Omelette",
    category: "Breakfast",
    mealType: "Vegetarian",
    calories: 136,
    protein: 18,
    carbs: 2,
    fats: 5,
    status: "Active",
    createdAt: "2025-12-04",
    description: "Low-calorie, high-protein breakfast option.",
    alternateFood: "Scrambled Tofu",
  },
  {
    id: 8,
    foodItem: "Turkey Wrap",
    category: "Lunch",
    mealType: "Non-Vegetarian",
    calories: 320,
    protein: 28,
    carbs: 35,
    fats: 8,
    status: "Active",
    createdAt: "2025-12-03",
    description: "Balanced meal with lean protein and whole grains.",
    alternateFood: "Chicken Wrap",
  },
  {
    id: 9,
    foodItem: "Avocado Toast",
    category: "Breakfast",
    mealType: "Vegan",
    calories: 290,
    protein: 8,
    carbs: 32,
    fats: 15,
    status: "Active",
    createdAt: "2025-12-02",
    description: "Healthy fats and fiber for sustained energy.",
    alternateFood: "Nut Butter Toast",
  },
  {
    id: 10,
    foodItem: "Grilled Vegetables",
    category: "Dinner",
    mealType: "Vegan",
    calories: 120,
    protein: 4,
    carbs: 18,
    fats: 4,
    status: "Active",
    createdAt: "2025-12-01",
    description: "Low-calorie, nutrient-dense side dish.",
    alternateFood: "Steamed Vegetables",
  },
];
