export const MOCK_EXERCISES = [
  {
    id: 1,
    title: "Squats",
    category: "Legs",
    difficulty: "Intermediate",
    mediaType: "GIF",
    status: "Active",
    createdAt: "2025-12-10",
  },
  {
    id: 2,
    title: "Push-ups",
    category: "Chest",
    difficulty: "Beginner",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-09",
  },
  {
    id: 3,
    title: "Pull-ups",
    category: "Back",
    difficulty: "Intermediate",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-08",
  },
  {
    id: 4,
    title: "Bench Press",
    category: "Chest",
    difficulty: "Intermediate",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-07",
  },
  {
    id: 5,
    title: "Deadlifts",
    category: "Back",
    difficulty: "Advanced",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-06",
  },
  {
    id: 6,
    title: "Shoulder Press",
    category: "Shoulders",
    difficulty: "Intermediate",
    mediaType: "Image",
    status: "Active",
    createdAt: "2025-12-05",
  },
  {
    id: 7,
    title: "Biceps Curl",
    category: "Arms",
    difficulty: "Beginner",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-04",
  },
  {
    id: 8,
    title: "Glute Bridge",
    category: "Glutes",
    difficulty: "Beginner",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-03",
  },
  {
    id: 9,
    title: "Glute Bridge",
    category: "Glutes",
    difficulty: "Beginner",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-03",
  },
  {
    id: 10,
    title: "Glute Bridge",
    category: "Glutes",
    difficulty: "Beginner",
    mediaType: "Video",
    status: "Active",
    createdAt: "2025-12-03",
  },
];

