export const MOCK_RECOVERY_CONTENT = [
  {
    id: 1,
    title: "Deep Breathing Exercise",
    category: "Breathing",
    contentType: "Video",
    status: "Active",
    createdAt: "2025-12-10",
    description: "A 5-minute guided deep breathing exercise to help reduce stress and improve recovery.",
  },
  {
    id: 2,
    title: "Full Body Stretching Routine",
    category: "Stretching",
    contentType: "Video",
    status: "Active",
    createdAt: "2025-12-09",
    description: "Comprehensive stretching routine targeting all major muscle groups for post-workout recovery.",
  },
  {
    id: 3,
    title: "Sleep Optimization Tips",
    category: "Sleep",
    contentType: "Article",
    status: "Active",
    createdAt: "2025-12-08",
    description: "Essential tips and strategies for improving sleep quality to enhance recovery.",
  },
  {
    id: 4,
    title: "Meditation for Recovery",
    category: "Meditation",
    contentType: "Audio",
    status: "Active",
    createdAt: "2025-12-07",
    description: "10-minute meditation session designed to promote mental and physical recovery.",
  },
  {
    id: 5,
    title: "Foam Rolling Techniques",
    category: "Self-Massage",
    contentType: "Video",
    status: "Active",
    createdAt: "2025-12-06",
    description: "Step-by-step guide to foam rolling for muscle recovery and flexibility.",
  },
  {
    id: 6,
    title: "Hydration Guide",
    category: "Nutrition",
    contentType: "Article",
    status: "Active",
    createdAt: "2025-12-05",
    description: "Understanding the importance of hydration in the recovery process.",
  },
  {
    id: 7,
    title: "Yoga Flow for Recovery",
    category: "Yoga",
    contentType: "Video",
    status: "Active",
    createdAt: "2025-12-04",
    description: "Gentle yoga flow sequence perfect for active recovery days.",
  },
  {
    id: 8,
    title: "Cold Therapy Benefits",
    category: "Therapy",
    contentType: "Article",
    status: "Active",
    createdAt: "2025-12-03",
    description: "Exploring the science behind cold therapy and its impact on recovery.",
  },
  {
    id: 9,
    title: "Progressive Muscle Relaxation",
    category: "Relaxation",
    contentType: "Audio",
    status: "Active",
    createdAt: "2025-12-02",
    description: "Guided audio session for progressive muscle relaxation and stress relief.",
  },
  {
    id: 10,
    title: "Recovery Nutrition Basics",
    category: "Nutrition",
    contentType: "Article",
    status: "Active",
    createdAt: "2025-12-01",
    description: "Essential nutrition strategies to support optimal recovery after workouts.",
  },
];
