export const MOCK_CONTENT_ITEMS = [
  {
    id: 1,
    title: "Privacy Policy",
    contentType: "Privacy Policy",
    status: "Published",
    excerpt: "How we collect, use, and protect your personal information.",
    lastUpdated: "2025-02-01",
    createdAt: "2025-01-10",
    body: "This privacy policy explains our practices regarding your data. We collect information you provide when registering, using the app, or contacting support. We use it to deliver services, improve the product, and communicate with you. We do not sell your data to third parties.",
  },
  {
    id: 2,
    title: "Terms & Conditions",
    contentType: "Terms & Conditions",
    status: "Published",
    excerpt: "Terms of use for the FOUR Score app and services.",
    lastUpdated: "2025-01-28",
    createdAt: "2025-01-10",
    body: "By using FOUR Score you agree to these terms. The service is provided as-is. You are responsible for your use and any content you submit. We may update these terms and will notify users of material changes.",
  },
  {
    id: 3,
    title: "FAQ – General",
    contentType: "FAQ",
    status: "Published",
    excerpt: "Frequently asked questions about the app and membership.",
    lastUpdated: "2025-02-03",
    createdAt: "2025-01-15",
    body: "Q: How do I reset my password? A: Use the Forgot Password link on the login screen. Q: Can I cancel my subscription? A: Yes, from Account Settings > Subscription.",
  },
  {
    id: 4,
    title: "About Us",
    contentType: "About Us",
    status: "Published",
    excerpt: "Learn about FOUR Score and our mission.",
    lastUpdated: "2025-01-20",
    createdAt: "2025-01-05",
    body: "FOUR Score is a fitness and wellness platform designed to help you achieve your goals with structured programs, nutrition guidance, and recovery content.",
  },
  {
    id: 5,
    title: "New Year Program Launch",
    contentType: "Announcement",
    status: "Published",
    excerpt: "Announcing our New Year fitness program starting January 15.",
    lastUpdated: "2025-01-12",
    createdAt: "2025-01-08",
    body: "We are excited to launch our New Year program with new workouts, meal plans, and recovery sessions. Available to all active members from January 15.",
  },
  {
    id: 6,
    title: "Maintenance Notice – Feb 10",
    contentType: "Announcement",
    status: "Draft",
    excerpt: "Scheduled maintenance window for app updates.",
    lastUpdated: "2025-02-05",
    createdAt: "2025-02-05",
    body: "We will perform scheduled maintenance on February 10, 2025 from 2:00 AM to 5:00 AM IST. The app may be briefly unavailable. We apologize for any inconvenience.",
  },
  {
    id: 7,
    title: "FAQ – Workouts",
    contentType: "FAQ",
    status: "Published",
    excerpt: "Common questions about workouts and exercise library.",
    lastUpdated: "2025-01-25",
    createdAt: "2025-01-18",
    body: "Q: How do I access the exercise library? A: Go to Programs > Exercise Library. Q: Can I download workouts for offline use? A: Yes, in the app settings under Offline Content.",
  },
  {
    id: 8,
    title: "Contact & Support",
    contentType: "Custom",
    status: "Published",
    excerpt: "How to get in touch with our support team.",
    lastUpdated: "2025-01-22",
    createdAt: "2025-01-12",
    body: "For support email support@fourscore.com or use the in-app chat. Response time is within 24 hours on business days.",
  },
];
